name: Release CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Setup libs
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        echo "THEOS=~/theos" >> $GITHUB_ENV

    - name: Make package(s)
      run: make package
        
    - name: Package preparation
      run: |
        echo "ROOTLESS=$(ls ./packages/ | grep -i 'iphoneos-arm64.deb')" >> $GITHUB_ENV
        echo "version=$(grep '^Version:' control | awk '{print $2}')" >> $GITHUB_ENV
    
    - name: Upload rootless artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ROOTLESS }}
        path: ./packages/${{ env.ROOTLESS }}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./packages/${{ env.ROOTLESS }}
        tag_name: v${{ env.version }}
